// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RegionColor {
	internal sealed partial class Vsix {
		public const string Id = "RegionColor.60e7aa9a-fcf4-48ed-b9bf-4c41869392c7";
		public const string Name = "RegionColor";
		public const string Description = @"Empty VSIX Project.";
		public const string Language = "en-US";
		public const string Version = "1.0";
		public const string Author = "裕介 川本";
		public const string Tags = "";
	}
}
